CREATE DATABASE IF NOT EXISTS LAB4;
USE LAB4;
CREATE TABLE IF NOT EXISTS TEAM(
	Name VARCHAR(30),
	Team VARCHAR(30),
	Salary INT,
    SICKLEAVE INT,
    ANNUALLEAVE INT
);
INSERT INTO TEAM VALUES("ADAMS","RESEARCH",28000,34,14);
INSERT INTO TEAM VALUES("WILKES","MARKETING",35000,40,10);
INSERT INTO TEAM VALUES("STOKES","MARKETING",32000,22,27);
INSERT INTO TEAM VALUES("MEZA","COLLECTIONS",43000,37,15);
INSERT INTO TEAM VALUES("MERRICK","RESEARCH",47000,35,18);
INSERT INTO TEAM VALUES("RICHARDSON","MARKETING",34500,21,26);
INSERT INTO TEAM VALUES("FURY","COLLECTIONS",35000,27,22);
INSERT INTO TEAM VALUES("PRECOURT","PR",41000,23,30);

SELECT * FROM TEAM;
SELECT Team, ROUND(AVG(Salary),2) AS "AVERAGE SALARY" FROM TEAM GROUP BY Team;
SELECT Team, ROUND(AVG(Salary),2) AS "AVERAGE SALARY" FROM TEAM GROUP BY Team HAVING AVG(Salary) < 39000;
SELECT Name,Salary FROM TEAM WHERE SICKLEAVE < 25 ORDER BY Name;
SELECT Team,COUNT(*) AS SAYILARI FROM TEAM WHERE SICKLEAVE < 30 GROUP BY Team;
SELECT Name AS NAMES FROM TEAM WHERE SICKLEAVE > ANNUALLEAVE;