CREATE DATABASE IF NOT EXISTS LAB2;
USE LAB2;
CREATE TABLE IF NOT EXISTS CHECKS(
    CHECK_ID INT AUTO_INCREMENT PRIMARY KEY,
    PAYEE VARCHAR(100),
    AMOUNT DOUBLE(10,2),
    REMARKS VARCHAR(100)
);

INSERT INTO CHECKS(PAYEE,AMOUNT,REMARKS) VALUES("Migros",270.12,"Groceries");
INSERT INTO CHECKS(PAYEE,AMOUNT,REMARKS) VALUES("Petrol Ofisi",105.00,"Gas (For Car)");
INSERT INTO CHECKS(PAYEE,AMOUNT,REMARKS) VALUES("TCDD",25.00,"Train to Konya");
INSERT INTO CHECKS(PAYEE,AMOUNT,REMARKS) VALUES("Turkcell",528.00,"Cellular Phone");
INSERT INTO CHECKS(PAYEE,AMOUNT,REMARKS) VALUES("Baskent Elektrik",113.78,"Electricity Bill");
INSERT INTO CHECKS(PAYEE,AMOUNT,REMARKS) VALUES("Flo",175.00,"Shoes");
INSERT INTO CHECKS(PAYEE,AMOUNT,REMARKS) VALUES("Migros",315.90,"Groceries");
INSERT INTO CHECKS(PAYEE,AMOUNT,REMARKS) VALUES("Allianz Sigorta",365.43,"Car Insurance");


SELECT CHECK_ID, PAYEE, AMOUNT FROM CHECKS WHERE PAYEE LIKE 'M%' OR PAYEE LIKE 'P%';
SELECT CHECK_ID, PAYEE, AMOUNT FROM CHECKS WHERE REMARKS LIKE '%CAR%';
SELECT DISTINCT PAYEE FROM CHECKS WHERE AMOUNT>200.00;
SELECT * FROM CHECKS ORDER BY AMOUNT DESC;
SELECT CHECK_ID, PAYEE, AMOUNT FROM CHECKS WHERE REMARKS LIKE '%SHOES%' OR REMARKS LIKE '%GROCERIES%';
