CREATE DATABASE IF NOT EXISTS LAB3;
USE LAB3;
CREATE TABLE IF NOT EXISTS STUDENTS(
	Student_ID INT,
    Student_Name VARCHAR(100),
    GPA DOUBLE(10,2),
    Age INT
);
INSERT INTO STUDENTS VALUES(17,"Ali K.",3.56,21);
INSERT INTO STUDENTS VALUES(11,"Mehmet S.",2.12,18);
INSERT INTO STUDENTS VALUES(25,"Ayhan D.",1.78,17);
INSERT INTO STUDENTS VALUES(27,"Fatma B.",2.45,17);
INSERT INTO STUDENTS VALUES(68,"Fulya K.",2.67,19);
INSERT INTO STUDENTS VALUES(62,"Ahmet T.",3.03,20);
INSERT INTO STUDENTS VALUES(42,"Yasemin K.",3.48,22);
INSERT INTO STUDENTS VALUES(45,"Nilüfer C.",3.12,18);
INSERT INTO STUDENTS VALUES(28,"Mehmet R.",2.89,23);
INSERT INTO STUDENTS VALUES(36,"Mustafa D.",1.56,18);

SELECT Student_Name AS "Student Name", Age FROM STUDENTS;
SELECT Student_Name AS "Student Name", Student_ID AS "Student ID" FROM STUDENTS WHERE GPA > 3.00;
SELECT ROUND(AVG(GPA),2) AS "AVERAGE GPA" FROM STUDENTS WHERE GPA > 2.50;
SELECT MAX(AGE) AS ELDEST FROM STUDENTS;
SELECT ROUND(AVG(Age),2) AS "AVERAGE AGE", ROUND(AVG(GPA),2) AS "AVERAGE GPA" FROM STUDENTS;
SELECT ROUND(AVG(Age),2) AS "AVERAGE AGE" FROM STUDENTS WHERE Student_Name LIKE "M%";
SELECT Student_ID AS "Student ID",Student_Name AS "Student Name",GPA, Age FROM STUDENTS ORDER BY AGE DESC;



-- SELECT Student_Name FROM STUDENTS WHERE Student_Name LIKE "M%";

-- Student_Name, GPA FROM STUDENTS WHERE GPA > 2.50;
-- SELECT COUNT(*) AS TOPLAM FROM STUDENTS WHERE GPA > 2.50;

-- SELECT * FROM STUDENTS;
-- SELECT COUNT(DISTINCT Student_Name) AS NEW_NAME FROM STUDENTS;
